export enum AuthorizationEnum {

    SER_ACCES = 'SER_ACCES',

    // Subscriptions
    SUB_ACTIVATE_BENCH = 'SUB_ACTIVATE_BENCH',
    SUB_ACTIVATE_PRODUCTION = 'SUB_ACTIVATE_PRODUCTION',
    SUB_CANCEL = 'SUB_CANCEL',
    SUB_CLIENT_CONTRIBUTOR_EDIT = 'SUB_CLIENT_CONTRIBUTOR_EDIT',
    SUB_CLIENT_EMAIL_EDIT = 'SUB_CLIENT_EMAIL_EDIT',
    SUB_CREATE = 'SUB_CREATE',
    SUB_CREATE_NEW_VERSION = 'SUB_CREATE_NEW_VERSION',
    SUB_DATA_RESTRICTED_UNLOCK = 'SUB_DATA_RESTRICTED_UNLOCK',
    SUB_DATA_ORDER = 'SUB_DATA_ORDER',
    SUB_DATE_BENCH_EDIT = 'SUB_DATE_BENCH_EDIT',
    SUB_DATE_PROD_EDIT = 'SUB_DATE_PROD_EDIT',
    SUB_DEFINITION_CREATE = 'SUB_DEFINITION_CREATE',
    SUB_DEFINITION_CORRECT = 'SUB_DEFINITION_CORRECT',
    SUB_DEFINITION_SAVE = 'SUB_DEFINITION_SAVE',
    SUB_DEFINITION_SUBMIT = 'SUB_DEFINITION_SUBMIT',
    SUB_DEFINITION_VALIDATE = 'SUB_DEFINITION_VALIDATE',
    SUB_DRAFT_CREATE = 'SUB_DRAFT_CREATE',
    SUB_DRAFT_SUBMIT = 'SUB_DRAFT_SUBMIT',
    SUB_DRAFT_VALIDATE = 'SUB_DRAFT_VALIDATE',
    SUB_EDIT_UNRESTRICTED = 'SUB_EDIT_UNRESTRICTED',
    SUB_IMPORT = 'SUB_IMPORT',
    SUB_INITIALIZATION_VALIDATE = 'SUB_INITIALIZATION_VALIDATE',
    SUB_MESSAGE_ADD = 'SUB_MESSAGE_ADD',
    SUB_PREVIEW = 'SUB_PREVIEW',
    SUB_SEARCH_UNRESTRICTED = 'SUB_SEARCH_UNRESTRICTED',
    SUB_VIEW = 'SUB_VIEW',
    SUB_VIEW_ACTIVE_VERSION = 'SUB_VIEW_ACTIVE_VERSION',
    SUB_VIEW_NEW_VERSION = 'SUB_VIEW_NEW_VERSION',

    // Console
    CONSOLE_USER_AUTH_VIEW = 'CONSOLE_USER_AUTH_VIEW',
    CONSOLE_MATRIX_COMPARE = 'CONSOLE_MATRIX_COMPARE',
    CONSOLE_MATRIX_RELOAD = 'CONSOLE_MATRIX_RELOAD',
    CONSOLE_MATRIX_VIEW = 'CONSOLE_MATRIX_VIEW',
    CONSOLE_VIEW = 'CONSOLE_VIEW'
}
